fail_fast: true
repos:

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.10
    hooks:
      # Run the linter.
      # - id: ruff
      #  args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: "isort (python)"
        types: [python]

  - repo: https://github.com/pre-commit/pre-commit
    rev: v3.2.0
    hooks:
      - id: validate_manifest
