"""add user group memberships

Revision ID: 03d3ec858fe7
Revises: 1a4fef66641d
Create Date: 2022-05-23 12:48:18.489491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "03d3ec858fe7"
down_revision = "1a4fef66641d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_group_memberships",
        sa.Column("user_group_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("info", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_group_id"],
            ["user_groups.id"],
            name="fk_user_group_memberships_user_group_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_user_group_memberships_user_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_group_id", "user_id"),
    )

    user_group_type = sa.Enum("CLASS", "CLUB", "OTHER", name="enum_user_group_type")
    user_group_type.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "user_group_memberships",
        sa.Column(
            "group_type",
            user_group_type,
            nullable=False,
            server_default="OTHER",
        ),
    )

    op.create_index(
        "index_users_per_group",
        "user_group_memberships",
        ["user_id", "user_group_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_user_group_memberships_group_type"),
        "user_group_memberships",
        ["group_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_group_memberships_group_type"),
        table_name="user_group_memberships",
    )
    op.drop_index("index_users_per_group", table_name="user_group_memberships")
    op.drop_table("user_group_memberships")
    # ### end Alembic commands ###
