"""add_hue_and_relationships

Revision ID: 07ad7ef7130e
Revises: 948ff66b643d
Create Date: 2022-01-18 16:26:23.741882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ad7ef7130e'
down_revision = '948ff66b643d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hues_name'), 'hues', ['name'], unique=True)
    op.create_table('hue_work_association',
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('hue_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Enum('PRIMARY', 'SECONDARY', 'TERTIARY', name='ordinal'), nullable=False),
    sa.ForeignKeyConstraint(['hue_id'], ['hues.id'], name='fk_hue_works_association_hue_id'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], name='fk_hue_works_association_work_id'),
    sa.PrimaryKeyConstraint('work_id', 'hue_id', 'ordinal')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hue_work_association')
    op.drop_index(op.f('ix_hues_name'), table_name='hues')
    op.drop_table('hues')
    # ### end Alembic commands ###
