"""Convert WorkInfo to JSON from mutabledict

Revision ID: 0821a5c94c12
Revises: 541f46c3aa65
Create Date: 2022-01-26 23:25:14.906968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0821a5c94c12'
down_revision = '541f46c3aa65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_series_author_id'), 'series', ['author_id'], unique=False)
    op.create_foreign_key('fk_authors_series', 'series', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_authors_series', 'series', type_='foreignkey')
    op.drop_index(op.f('ix_series_author_id'), table_name='series')
    op.drop_column('series', 'author_id')
    # ### end Alembic commands ###
