"""Add pg vector extension

Revision ID: 0cf99e2a9dfb
Revises: 01bf3f33a0c8
Create Date: 2024-05-07 19:58:02.697509

"""

import sqlalchemy as sa
from alembic_utils.pg_extension import PGExtension
from sqlalchemy import text as sql_text

from alembic import op

# revision identifiers, used by Alembic.
revision = "0cf99e2a9dfb"
down_revision = "01bf3f33a0c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_vector = PGExtension(schema="public", signature="vector")
    op.create_entity(public_vector)

    public_fuzzystrmatch = PGExtension(schema="public", signature="fuzzystrmatch")
    op.drop_entity(public_fuzzystrmatch)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_fuzzystrmatch = PGExtension(schema="public", signature="fuzzystrmatch")
    op.create_entity(public_fuzzystrmatch)

    public_vector = PGExtension(schema="public", signature="vector")
    op.drop_entity(public_vector)

    # ### end Alembic commands ###
