"""Revive labelset timestamps but better

Revision ID: 1160a11c1f73
Revises: 06d5f42f87ea
Create Date: 2022-03-09 22:48:38.603753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1160a11c1f73"
down_revision = "06d5f42f87ea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "labelsets",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "labelsets",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("labelsets", "updated_at")
    op.drop_column("labelsets", "created_at")
    # ### end Alembic commands ###
