"""make edition:work_id nullable

Revision ID: 128753c814af
Revises: 2976a4ff1b24
Create Date: 2022-02-21 14:46:37.756884

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "128753c814af"
down_revision = "2976a4ff1b24"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("editions", "work_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("editions", "work_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
