"""Add VertexAI orgin

Revision ID: 156d8781d7b8
Revises: 7dd85b891761
Create Date: 2024-06-09 18:29:19.197616

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "156d8781d7b8"
down_revision = "7dd85b891761"
branch_labels = None
depends_on = None
old_values = """'HUMAN', 'GPT4', 'PREDICTED_NIELSEN', 'NIELSEN_CBMC', 'NIELSEN_BIC', 'NIELSEN_THEMA', 'NIELSEN_IA', 'NIELSEN_RA', 'CLUSTER_RELEVANCE', 'CLUSTER_ZAINAB', 'OTHER'"""
new = sa.Enum(
    "HUMAN",
    "GPT4",
    "PREDICTED_NIELSEN",
    "NIELSEN_CBMC",
    "NIELSEN_BIC",
    "NIELSEN_THEMA",
    "NIELSEN_IA",
    "NIELSEN_RA",
    "CLUSTER_RELEVANCE",
    "CLUSTER_ZAINAB",
    "OTHER",
    "VERTEXAI",
    name="labelorigin",
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE labelorigin RENAME TO labelorigin_old")
    op.execute(
        "CREATE TYPE labelorigin AS ENUM('HUMAN', 'GPT4', 'PREDICTED_NIELSEN', 'NIELSEN_CBMC', 'NIELSEN_BIC', 'NIELSEN_THEMA', 'NIELSEN_IA', 'NIELSEN_RA', 'CLUSTER_RELEVANCE', 'CLUSTER_ZAINAB', 'OTHER', 'VERTEXAI')"
    )
    op.alter_column(
        "labelsets",
        "age_origin",
        type_=new,
        postgresql_using="age_origin::text::labelorigin",
    )
    op.alter_column(
        "labelsets",
        "reading_ability_origin",
        type_=new,
        postgresql_using="reading_ability_origin::text::labelorigin",
    )
    op.alter_column(
        "labelsets",
        "summary_origin",
        type_=new,
        postgresql_using="summary_origin::text::labelorigin",
    )
    op.alter_column(
        "labelsets",
        "hue_origin",
        type_=new,
        postgresql_using="hue_origin::text::labelorigin",
    )
    op.alter_column(
        "labelsets",
        "recommend_status_origin",
        type_=new,
        postgresql_using="recommend_status_origin::text::labelorigin",
    )
    op.execute("DROP TYPE labelorigin_old")
    # ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ...
    # ### end Alembic commands ###
