"""add collection timestamp update func

Revision ID: 1e26ba3d64a3
Revises: 9cfb4e3c02b2
Create Date: 2023-01-10 13:45:18.720758

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "1e26ba3d64a3"
down_revision = "9cfb4e3c02b2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "collection_items_collection_id_fkey", "collection_items", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_collection_items_collection_id",
        "collection_items",
        "collections",
        ["collection_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION update_collections_function()
        RETURNS TRIGGER AS $$
        BEGIN
          UPDATE collections
          SET updated_at = NOW()
          WHERE collections.id = NEW.collection_id;
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_collection_items_collection_id", "collection_items", type_="foreignkey"
    )
    op.create_foreign_key(
        "collection_items_collection_id_fkey",
        "collection_items",
        "collections",
        ["collection_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.execute("DROP FUNCTION update_collections_function")
    # ### end Alembic commands ###
