"""add supporter table and relationships

Revision ID: 285383bc2a2c
Revises: f99ef8f753ac
Create Date: 2023-02-18 14:24:27.026450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "285383bc2a2c"
down_revision = "f99ef8f753ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "supporters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("supporter_info", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"], ["users.id"], name="fk_supporter_inherits_user", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "supporter_reader_association",
        sa.Column("supporter_id", sa.UUID(), nullable=False),
        sa.Column("reader_id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reader_id"], ["readers.id"], name="fk_supporter_reader_assoc_reader_id"
        ),
        sa.ForeignKeyConstraint(
            ["supporter_id"],
            ["users.id"],
            name="fk_supporter_reader_assoc_supporter_id",
        ),
        sa.PrimaryKeyConstraint("supporter_id", "reader_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("supporter_reader_association")
    op.drop_table("supporters")
    # ### end Alembic commands ###
