"""Drop user email requirement

Revision ID: 2b2edef753de
Revises: 2b4a649442a7
Create Date: 2022-05-21 15:21:58.336657

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2b2edef753de"
down_revision = "2b4a649442a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
