"""Add defferable unique constraint for booklist order

Revision ID: 2b4a649442a7
Revises: 51f197c74186
Create Date: 2022-05-19 18:02:38.472062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2b4a649442a7"
down_revision = "51f197c74186"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("index_booklist_ordered", table_name="book_list_works")
    op.create_index(
        "index_booklist_ordered",
        "book_list_works",
        ["booklist_id", "order_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("index_booklist_ordered", table_name="book_list_works")
    op.create_index(
        "index_booklist_ordered",
        "book_list_works",
        ["booklist_id", "order_id"],
        unique=False,
    )
    # ### end Alembic commands ###
