"""add class groups

Revision ID: 2c2432bf570b
Revises: 52a7389ccfa6
Create Date: 2022-05-30 22:47:38.883039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2c2432bf570b"
down_revision = "52a7389ccfa6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "class_groups",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("school_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("join_code", sa.String(length=6), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["school_id"], ["schools.id"], name="fk_class_groups_school"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_class_groups_school_id"), "class_groups", ["school_id"], unique=False
    )
    op.add_column(
        "students", sa.Column("class_group_id", postgresql.UUID(), nullable=False)
    )
    op.create_index(
        op.f("ix_students_class_group_id"), "students", ["class_group_id"], unique=False
    )
    op.create_foreign_key(
        "fk_student_class_group", "students", "class_groups", ["class_group_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_student_class_group", "students", type_="foreignkey")
    op.drop_index(op.f("ix_students_class_group_id"), table_name="students")
    op.drop_column("students", "class_group_id")
    op.drop_index(op.f("ix_class_groups_school_id"), table_name="class_groups")
    op.drop_table("class_groups")
    # ### end Alembic commands ###
