"""Index editions in collection items

Revision ID: 2dfabf8db695
Revises: ded4fe3ab668
Create Date: 2022-01-16 23:41:32.230754

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2dfabf8db695"
down_revision = "ded4fe3ab668"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "unique_editions_per_collection", "collection_items", type_="unique"
    )
    op.create_index(
        "index_editions_per_collection",
        "collection_items",
        ["school_id", "edition_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("index_editions_per_collection", table_name="collection_items")
    op.create_unique_constraint(
        "unique_editions_per_collection",
        "collection_items",
        ["school_id", "edition_id"],
    )
    # ### end Alembic commands ###
