"""add_current_flow_id_to_conversation_session

Revision ID: 3252097e86db
Revises: cdb8033410a7
Create Date: 2026-01-11 13:42:07.984902

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3252097e86db"
down_revision = "cdb8033410a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversation_sessions", sa.Column("current_flow_id", sa.UUID(), nullable=True)
    )
    op.create_foreign_key(
        "fk_session_current_flow",
        "conversation_sessions",
        "flow_definitions",
        ["current_flow_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_session_current_flow", "conversation_sessions", type_="foreignkey"
    )
    op.drop_column("conversation_sessions", "current_flow_id")
    # ### end Alembic commands ###
