"""make username non-nullable for readers

Revision ID: 35112b0ae03e
Revises: 77c90a741ba7
Create Date: 2022-06-02 15:50:35.584586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "35112b0ae03e"
down_revision = "77c90a741ba7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "readers",
        "username",
        existing_type=sa.VARCHAR(),
        nullable=True,
        server_default="update_me",
    )
    op.alter_column("readers", "username", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("readers", "username", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
