"""Upgrade Genre table

Revision ID: 38ba808dac76
Revises: af40ae7f818d
Create Date: 2022-03-06 19:34:42.859504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "38ba808dac76"
down_revision = "af40ae7f818d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    genresource = sa.Enum(
        "BISAC", "BIC", "THEMA", "LOCSH", "HUMAN", "OTHER", name="genresource"
    )
    # This will create the enum if it's not already present which is helpful
    genresource.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "genres",
        sa.Column(
            "source",
            genresource,
            nullable=False,
            server_default="OTHER",
        ),
    )
    op.drop_constraint("genres_bisac_code_key", "genres", type_="unique")
    op.drop_column("genres", "bisac_code")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "genres",
        sa.Column(
            "bisac_code", sa.VARCHAR(length=12), autoincrement=False, nullable=True
        ),
    )
    op.create_unique_constraint("genres_bisac_code_key", "genres", ["bisac_code"])
    op.drop_column("genres", "source")
    op.execute("DROP TYPE genresource")
    genresource = sa.Enum(name="genresource")
    genresource.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
