"""Title key for series

Revision ID: 3b1027ac115a
Revises: 42eae10108f7
Create Date: 2022-03-06 23:47:09.006682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3b1027ac115a"
down_revision = "42eae10108f7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "series",
        sa.Column(
            "title_key",
            sa.String(length=512),
            sa.Computed(
                "LOWER(REGEXP_REPLACE(LOWER(title), '(^(\\w*the ))|(^(\\w*a ))|[^a-z0-9]', '', 'g'))",
            ),
            nullable=True,
        ),
    )
    op.create_index(op.f("ix_series_title_key"), "series", ["title_key"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_series_title_key"), table_name="series")
    op.drop_column("series", "title_key")
    # ### end Alembic commands ###
