"""Add subtitle to editions and works

Revision ID: 3c1e2888884d
Revises: dd5c99007a29
Create Date: 2022-03-08 12:40:20.819628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c1e2888884d'
down_revision = 'dd5c99007a29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('editions', sa.Column('edition_subtitle', sa.String(length=512), nullable=True))
    op.add_column('works', sa.Column('subtitle', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'subtitle')
    op.drop_column('editions', 'edition_subtitle')
    # ### end Alembic commands ###
