"""trigger to generate edition title coalesce

Revision ID: 3cc9f3831b7b
Revises: 700693098e41
Create Date: 2023-01-19 15:32:26.436442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3cc9f3831b7b"
down_revision = "700693098e41"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("editions", sa.Column("title", sa.String(length=512), nullable=True))
    op.create_index(op.f("ix_editions_title"), "editions", ["title"], unique=False)
    op.execute(
        """
        UPDATE editions SET title = COALESCE(editions.edition_title, works.title)
        FROM works
        WHERE editions.work_id = works.id;
        """
    )
    op.execute(
        """
    CREATE OR REPLACE FUNCTION update_edition_title() RETURNS TRIGGER AS $$
    BEGIN
        UPDATE editions SET title = COALESCE(editions.edition_title, works.title)
        FROM works
        WHERE editions.work_id = works.id AND (NEW.edition_title IS NOT NULL OR NEW.work_id IS NOT NULL);
        RETURN NULL;
    END;
    $$ LANGUAGE plpgsql;
    """
    )
    op.execute(
        """
    CREATE OR REPLACE FUNCTION update_edition_title_from_work() RETURNS TRIGGER AS $$
    BEGIN
        UPDATE editions SET title = COALESCE(editions.edition_title, works.title)
        FROM works
        WHERE editions.work_id = works.id AND (NEW.title IS NOT NULL);
        RETURN NULL;
    END;
    $$ LANGUAGE plpgsql;
    """
    )
    op.execute(
        """
    CREATE TRIGGER update_edition_title_trigger
    AFTER INSERT OR UPDATE OF edition_title, work_id ON editions
    FOR EACH ROW
    EXECUTE FUNCTION update_edition_title();

    CREATE TRIGGER update_edition_title_from_work_trigger
    AFTER INSERT OR UPDATE OF title ON works
    FOR EACH ROW
    EXECUTE FUNCTION update_edition_title_from_work();
    """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_editions_title"), table_name="editions")
    op.drop_column("editions", "title")
    op.execute("DROP TRIGGER update_edition_title_trigger ON editions")
    op.execute("DROP TRIGGER update_edition_title_from_work_trigger ON works")
    op.execute("DROP FUNCTION update_edition_title")
    op.execute("DROP FUNCTION update_edition_title_from_work")
    # ### end Alembic commands ###
