"""rename collection_item counts

Revision ID: 427891a30fee
Revises: aaa2118c61fd
Create Date: 2022-01-19 15:30:28.341057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "427891a30fee"
down_revision = "aaa2118c61fd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "collection_items",
        "copies_on_loan",
        nullable=False,
        new_column_name="copies_total",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "collection_items",
        "copies_total",
        nullable=False,
        new_column_name="copies_on_loan",
    )
    # ### end Alembic commands ###
