"""Title changes to works and editions

Revision ID: 42eae10108f7
Revises: e4529adaa763
Create Date: 2022-03-06 23:42:01.027574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "42eae10108f7"
down_revision = "e4529adaa763"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "editions", sa.Column("leading_article", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "works", sa.Column("leading_article", sa.String(length=20), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("works", "leading_article")
    op.drop_column("editions", "leading_article")
    # ### end Alembic commands ###
