"""Alter edition title update functions

Revision ID: 4357602fafb2
Revises: e5ac1e7a54cd
Create Date: 2023-02-17 10:37:33.577725

"""
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text

from alembic import op

# revision identifiers, used by Alembic.
revision = "4357602fafb2"
down_revision = "3cc9f3831b7b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_update_edition_title = PGFunction(
        schema="public",
        signature="update_edition_title()",
        definition="returns trigger LANGUAGE plpgsql\n    AS $function$\n    BEGIN\n    UPDATE editions SET title = COALESCE(editions.edition_title, works.title)\n    FROM works\n    WHERE editions.work_id = NEW.id AND (NEW.edition_title IS NOT NULL OR NEW.work_id IS NOT NULL);\n    RETURN NULL;\n    END;\n    $function$",
    )
    op.replace_entity(public_update_edition_title)

    public_update_edition_title_from_work = PGFunction(
        schema="public",
        signature="update_edition_title_from_work()",
        definition="returns trigger LANGUAGE plpgsql\n    AS $function$\n    BEGIN\n        UPDATE editions SET title = COALESCE(editions.edition_title, works.title)\n        FROM works\n        WHERE editions.work_id = NEW.id AND (NEW.title IS NOT NULL);\n        RETURN NULL;\n    END;\n    $function$",
    )
    op.replace_entity(public_update_edition_title_from_work)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_update_edition_title_from_work = PGFunction(
        schema="public",
        signature="update_edition_title_from_work()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n    BEGIN\n        UPDATE editions SET title = COALESCE(editions.edition_title, works.title)\n        FROM works\n        WHERE editions.work_id = works.id AND (NEW.title IS NOT NULL);\n        RETURN NULL;\n    END;\n    $function$",
    )
    op.replace_entity(public_update_edition_title_from_work)
    public_update_edition_title = PGFunction(
        schema="public",
        signature="update_edition_title()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n    BEGIN\n        UPDATE editions SET title = COALESCE(editions.edition_title, works.title)\n        FROM works\n        WHERE editions.work_id = works.id AND (NEW.edition_title IS NOT NULL OR NEW.work_id IS NOT NULL);\n        RETURN NULL;\n    END;\n    $function$",
    )
    op.replace_entity(public_update_edition_title)
    # ### end Alembic commands ###
