"""add author to series

Revision ID: 47a4929dddb7
Revises: e7516505ec52
Create Date: 2022-01-25 14:48:10.577199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a4929dddb7'
down_revision = 'e7516505ec52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_series_author_id'), 'series', ['author_id'], unique=False)
    op.create_foreign_key('fk_authors_series', 'series', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_authors_series', 'series', type_='foreignkey')
    op.drop_index(op.f('ix_series_author_id'), table_name='series')
    op.drop_column('series', 'author_id')
    # ### end Alembic commands ###
