"""Modify collection items

Revision ID: 48c28918b620
Revises: 72687253de14
Create Date: 2021-12-29 17:10:34.428610

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "48c28918b620"
down_revision = "72687253de14"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "collection_items", "school_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "collection_items", "edition_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "collection_items", "edition_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "collection_items", "school_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
