"""Require user is_active

Revision ID: 4f7496e524b6
Revises: 6af537b94a8a
Create Date: 2023-02-20 21:22:27.646524

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4f7496e524b6"
down_revision = "6af537b94a8a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
