"""add BISAC code to genre

Revision ID: 541f46c3aa65
Revises: 47a4929dddb7
Create Date: 2022-01-25 15:52:45.350567

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "541f46c3aa65"
down_revision = "47a4929dddb7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("genres", sa.Column("bisac_code", sa.String(length=8), nullable=True))
    op.create_unique_constraint(None, "genres", ["bisac_code"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "genres", type_="unique")
    op.drop_column("genres", "bisac_code")
    # ### end Alembic commands ###
