"""Remove genre model

Revision ID: 57c40ea9ffa7
Revises: b19f3360a95b
Create Date: 2022-03-10 10:53:22.228876

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "57c40ea9ffa7"
down_revision = "b19f3360a95b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("labelset_genre_association")
    op.drop_index("ix_genres_name", table_name="genres")
    op.drop_table("genres")
    op.execute("DROP TYPE genresource")
    genresource = sa.Enum(name="genresource")
    genresource.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genres",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('genres_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column(
            "source",
            postgresql.ENUM(
                "BISAC", "BIC", "THEMA", "LOCSH", "HUMAN", "OTHER", name="genresource"
            ),
            server_default=sa.text("'OTHER'::genresource"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="genres_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_genres_name", "genres", ["name"], unique=False)
    op.create_table(
        "labelset_genre_association",
        sa.Column("labelset_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("genre_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["genre_id"], ["genres.id"], name="fk_labelset_genre_association_genre_id"
        ),
        sa.ForeignKeyConstraint(
            ["labelset_id"],
            ["labelsets.id"],
            name="fk_labelset_genre_association_labelset_id",
        ),
    )
    # ### end Alembic commands ###
