"""add supporter nickname

Revision ID: 590a6fb0b2c7
Revises: c82cfb47da40
Create Date: 2023-02-21 16:31:05.873767

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "590a6fb0b2c7"
down_revision = "c82cfb47da40"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "supporter_reader_association",
        sa.Column("supporter_nickname", sa.String(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("supporter_reader_association", "supporter_nickname")
    # ### end Alembic commands ###
