"""Update name_key computation

Revision ID: 63b677b9d91f
Revises: 82379c041af6
Create Date: 2022-03-08 21:38:07.347229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "63b677b9d91f"
down_revision = "82379c041af6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_authors_name_key", table_name="authors")
    op.drop_column("authors", "name_key")
    op.drop_index("ix_illustrators_name_key", table_name="illustrators")
    op.drop_column("illustrators", "name_key")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "illustrators",
        sa.Column(
            "name_key",
            sa.VARCHAR(length=400),
            sa.Computed(
                "lower(regexp_replace(((first_name)::text || (last_name)::text), '\\W|_'::text, ''::text, 'g'::text))",
                persisted=True,
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        "ix_illustrators_name_key", "illustrators", ["name_key"], unique=False
    )
    op.add_column(
        "authors",
        sa.Column(
            "name_key",
            sa.VARCHAR(length=400),
            sa.Computed(
                "lower(regexp_replace(((first_name)::text || (last_name)::text), '\\W|_'::text, ''::text, 'g'::text))",
                persisted=True,
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index("ix_authors_name_key", "authors", ["name_key"], unique=False)
    # ### end Alembic commands ###
