"""Adjust author names

Revision ID: 6cf3902b1f75
Revises: cef2d44dd799
Create Date: 2021-12-27 16:37:01.800147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf3902b1f75'
down_revision = 'cef2d44dd799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('full_name', sa.String(length=400), nullable=False))
    op.create_index(op.f('ix_authors_last_name'), 'authors', ['last_name'], unique=False)
    op.drop_column('authors', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('first_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_authors_last_name'), table_name='authors')
    op.drop_column('authors', 'full_name')
    # ### end Alembic commands ###
