"""model + relationships collectionitemactivity

Revision ID: 6cf4a18a99ed
Revises: 97cd77cff343
Create Date: 2023-01-13 20:51:43.211806

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "6cf4a18a99ed"
down_revision = "97cd77cff343"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection_item_activity_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("collection_item_id", sa.Integer(), nullable=False),
        sa.Column("reader_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "UNREAD",
                "TO_READ",
                "NOT_INTERESTED",
                "READING",
                "STOPPED_READING",
                "READ",
                name="enum_collection_item_read_status",
            ),
            nullable=False,
        ),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_item_id"],
            ["collection_items.id"],
            name="fk_collection_item_activity_collection_item_id",
        ),
        sa.ForeignKeyConstraint(
            ["reader_id"], ["readers.id"], name="fk_collection_item_activity_reader"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_collection_item_activity_log_collection_item_id"),
        "collection_item_activity_log",
        ["collection_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collection_item_activity_log_status"),
        "collection_item_activity_log",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_collection_item_activity_log_status"),
        table_name="collection_item_activity_log",
    )
    op.drop_index(
        op.f("ix_collection_item_activity_log_collection_item_id"),
        table_name="collection_item_activity_log",
    )
    op.drop_table("collection_item_activity_log")
    op.execute("DROP TYPE enum_collection_item_read_status")
    # ### end Alembic commands ###
