"""Add service account table

Revision ID: 72687253de14
Revises: e4f0666727f3
Create Date: 2021-12-28 11:55:31.393459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "72687253de14"
down_revision = "e4f0666727f3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_accounts",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("BACKEND", "LMS", "SCHOOL", "KIOSK", name="serviceaccounttype"),
            nullable=False,
        ),
        sa.Column("info", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_service_accounts_id"), "service_accounts", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_service_accounts_type"), "service_accounts", ["type"], unique=False
    )
    op.create_table(
        "service_account_school_association",
        sa.Column("service_account_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("school_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name="fk_service_account_school_association_school",
        ),
        sa.ForeignKeyConstraint(
            ["service_account_id"],
            ["service_accounts.id"],
            name="fk_service_account_school_association_service_account",
        ),
        sa.PrimaryKeyConstraint("service_account_id", "school_id"),
    )
    op.add_column(
        "events",
        sa.Column("service_account_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(
        "fk_event_service_account",
        "events",
        "service_accounts",
        ["service_account_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_event_service_account", "events", type_="foreignkey")
    op.drop_constraint("fk_event_user", "events", type_="foreignkey")
    op.drop_column("events", "service_account_id")
    op.drop_table("service_account_school_association")
    op.drop_index(op.f("ix_service_accounts_type"), table_name="service_accounts")
    op.drop_index(op.f("ix_service_accounts_id"), table_name="service_accounts")
    op.drop_table("service_accounts")
    op.execute("DROP TYPE serviceaccounttype")
    # ### end Alembic commands ###
