"""add readerprofiles

Revision ID: 7494cd6f2a17
Revises: bef0307ae2c2
Create Date: 2022-08-31 19:05:21.935650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7494cd6f2a17"
down_revision = "bef0307ae2c2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "readerprofiles",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("gems", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("parent_id", postgresql.UUID(), nullable=True),
        sa.Column("huey_attributes", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["parents.id"], name="fk_reader_profile_parent"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_readerprofiles_gems"), "readerprofiles", ["gems"], unique=False
    )
    op.create_index(op.f("ix_readerprofiles_id"), "readerprofiles", ["id"], unique=True)
    op.create_index(
        op.f("ix_readerprofiles_parent_id"),
        "readerprofiles",
        ["parent_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_readerprofiles_parent_id"), table_name="readerprofiles")
    op.drop_index(op.f("ix_readerprofiles_id"), table_name="readerprofiles")
    op.drop_index(op.f("ix_readerprofiles_gems"), table_name="readerprofiles")
    op.drop_table("readerprofiles")
    # ### end Alembic commands ###
