"""Add first name and initial to reader table

Revision ID: 77c90a741ba7
Revises: 3076bbdb14d6
Create Date: 2022-06-02 15:03:17.406912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "77c90a741ba7"
down_revision = "3076bbdb14d6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "readers",
        sa.Column("first_name", sa.String(), server_default="", nullable=False),
    )
    op.add_column(
        "readers",
        sa.Column("last_name_initial", sa.String(), server_default="", nullable=False),
    )
    op.alter_column("readers", "first_name", server_default=None)
    op.alter_column("readers", "last_name_initial", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("readers", "last_name_initial")
    op.drop_column("readers", "first_name")
    # ### end Alembic commands ###
