"""Add bookbot type to school

Revision ID: 7a347c5cd18e
Revises: 487b983bc323
Create Date: 2022-02-09 02:44:44.606954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '7a347c5cd18e'
down_revision = '487b983bc323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    schoolbookbottype = sa.Enum('SCHOOL_BOOKS', 'HUEY_BOOKS', name='schoolbookbottype')
    # This will create the enum if it's not already present which is helpful
    schoolbookbottype.create(op.get_bind(), checkfirst=True)
    op.add_column('schools', sa.Column('bookbot_type', schoolbookbottype, nullable=False, server_default="HUEY_BOOKS"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'bookbot_type')
    op.execute('DROP TYPE schoolbookbottype')
    schoolbookbottype = sa.Enum(name='schoolbookbottype')
    schoolbookbottype.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
