"""Add school subscription column

Revision ID: 7dd85b891761
Revises: 362449eb9849
Create Date: 2024-05-13 21:50:47.992374

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7dd85b891761"
down_revision = "362449eb9849"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscriptions", sa.Column("school_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_subscriptions_school_id"), "subscriptions", ["school_id"], unique=False
    )
    op.create_foreign_key(
        "fk_school_stripe_subscription",
        "subscriptions",
        "schools",
        ["school_id"],
        ["wriveted_identifier"],
        ondelete="CASCADE",
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_school_stripe_subscription", "subscriptions", type_="foreignkey"
    )
    op.drop_index(op.f("ix_subscriptions_school_id"), table_name="subscriptions")
    op.drop_column("subscriptions", "school_id")
    # ### end Alembic commands ###
