"""School:admin and school:student differentiation

Revision ID: 7f02230c1599
Revises: ef00fddd2595
Create Date: 2022-02-08 21:06:17.919567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f02230c1599'
down_revision = 'ef00fddd2595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('admin_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('fk_school_admin', 'schools', 'users', ['admin_id'], ['id'])
    op.add_column('users', sa.Column('school_id_as_admin', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_admin_school', 'users', 'schools', ['school_id_as_admin'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_admin_school', 'users', type_='foreignkey')
    op.drop_column('users', 'school_id_as_admin')
    op.drop_constraint('fk_school_admin', 'schools', type_='foreignkey')
    op.drop_column('schools', 'admin_id')
    # ### end Alembic commands ###
