"""add communication flags to supporter association

Revision ID: 820e104b78f9
Revises: 40c5b7fae8e1
Create Date: 2023-02-18 22:56:26.012225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820e104b78f9'
down_revision = '40c5b7fae8e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
