"""rename reading_preferences

Revision ID: 88eceff70bcd
Revises: 90aeb305955e
Create Date: 2022-06-20 16:12:42.389438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "88eceff70bcd"
down_revision = "90aeb305955e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("readers", "reading_preferences", new_column_name="huey_attributes")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("readers", "huey_attributes", new_column_name="reading_preferences")
    # ### end Alembic commands ###
