"""nullable first name and initial

Revision ID: 88f57e4323b4
Revises: 00f9ceaa60e5
Create Date: 2022-08-12 12:16:55.302702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "88f57e4323b4"
down_revision = "00f9ceaa60e5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("readers", "first_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "readers", "last_name_initial", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # first_name: replace all content beyond the last whitespace in full name with empty
    # last_name_initial: replace entire body with a capture group that seeks the first character after the last instance of whitespace
    # example: name: James Earl Jones = first_name: James Earl, last_name_initial: J
    op.execute(
        """
        update readers
        set    first_name = regexp_replace(name, '\s+\S+$', ''),
        last_name_initial = upper(regexp_replace(name, '^.*\s+(\S).*$', '\1'))
        from   users
        where  users.id = readers.id;
    """
    )

    op.alter_column(
        "readers", "last_name_initial", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("readers", "first_name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
