"""update booklists for public+sharing

Revision ID: 89d877a37997
Revises: 590a6fb0b2c7
Create Date: 2023-03-06 14:06:24.796711

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "89d877a37997"
down_revision = "590a6fb0b2c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book_lists",
        sa.Column("slug", sa.String(length=200), nullable=True),
    )
    booklistsharingtype = sa.Enum(
        "PRIVATE", "RESTRICTED", "PUBLIC", name="enum_book_list_sharing"
    )
    # This will create the enum if it's not already present which is helpful
    booklistsharingtype.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "book_lists",
        sa.Column(
            "sharing",
            booklistsharingtype,
            server_default="PRIVATE",
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_book_lists_sharing"), "book_lists", ["sharing"], unique=False
    )
    op.create_index(op.f("ix_book_lists_slug"), "book_lists", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_book_lists_slug"), table_name="book_lists")
    op.drop_index(op.f("ix_book_lists_sharing"), table_name="book_lists")
    op.drop_column("book_lists", "sharing")
    op.drop_column("book_lists", "slug")
    op.execute("DROP TYPE enum_book_list_sharing")
    booklistsharingtype = sa.Enum(name="enum_book_list_sharing")
    booklistsharingtype.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
