"""Remove illustrator temporarily

Revision ID: 933bcb167be6
Revises: 541f46c3aa65
Create Date: 2022-01-27 13:38:13.685125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "933bcb167be6"
down_revision = "541f46c3aa65"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("illustrator_edition_association")
    op.drop_table("illustrators")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "illustrators",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("first_name", sa.String(length=200), nullable=True),
        sa.Column("last_name", sa.String(length=200), nullable=False),
        sa.Column(
            "full_name",
            sa.String(length=400),
            sa.Computed(
                "COALESCE(first_name || ' ', '') || last_name",
            ),
            nullable=True,
        ),
        sa.Column("info", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "illustrator_edition_association",
        sa.Column("edition_id", sa.Integer(), nullable=False),
        sa.Column("illustrator_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["edition_id"],
            ["editions.id"],
            name="fk_illustrator_editions_assoc_edition_id",
        ),
        sa.ForeignKeyConstraint(
            ["illustrator_id"],
            ["illustrators.id"],
            name="fk_illustrator_editions_assoc_illustrator_id",
        ),
        sa.PrimaryKeyConstraint("edition_id", "illustrator_id"),
    )
    # ### end Alembic commands ###
