"""Adjust editions to allow nullable covers and titles

Revision ID: 956cf011085f
Revises: 8db19b335b7e
Create Date: 2021-12-27 10:56:24.478952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956cf011085f'
down_revision = '8db19b335b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('editions', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('editions', 'cover_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_index('ix_editions_title', table_name='editions')
    op.create_index(op.f('ix_editions_ISBN'), 'editions', ['ISBN'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_editions_ISBN'), table_name='editions')
    op.create_index('ix_editions_title', 'editions', ['title'], unique=False)
    op.alter_column('editions', 'cover_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('editions', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
