"""add last_checkout_session_id to subscription, nullable user

Revision ID: 9582b1d4da88
Revises: e4c494dc08fb
Create Date: 2022-12-15 19:14:44.580926

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "9582b1d4da88"
down_revision = "e4c494dc08fb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions",
        sa.Column("latest_checkout_session_id", sa.String(), nullable=True),
    )
    op.alter_column(
        "subscriptions", "user_id", existing_type=postgresql.UUID(), nullable=True
    )
    op.create_index(
        op.f("ix_subscriptions_latest_checkout_session_id"),
        "subscriptions",
        ["latest_checkout_session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_subscriptions_latest_checkout_session_id"), table_name="subscriptions"
    )
    op.alter_column(
        "subscriptions", "user_id", existing_type=postgresql.UUID(), nullable=False
    )
    op.drop_column("subscriptions", "latest_checkout_session_id")
    # ### end Alembic commands ###
