"""unique editions per collection

Revision ID: 95df158f258b
Revises: 3534e992a7b6
Create Date: 2022-11-24 17:32:11.695786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "95df158f258b"
down_revision = "3534e992a7b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "collection_items",
        "collection_id",
        existing_type=postgresql.UUID(),
        nullable=False,
    )
    op.drop_index("index_editions_per_collection", table_name="collection_items")
    op.create_unique_constraint(
        "unique_editions_per_collection",
        "collection_items",
        ["collection_id", "edition_isbn"],
    )
    op.drop_constraint(
        "fk_collection_items_collection_id", "collection_items", type_="foreignkey"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_collection_items_collection_id",
        "collection_items",
        "collections",
        ["collection_id"],
        ["id"],
    )
    op.drop_constraint(
        "unique_editions_per_collection", "collection_items", type_="unique"
    )
    op.create_index(
        "index_editions_per_collection",
        "collection_items",
        ["collection_id", "edition_isbn"],
        unique=False,
    )
    op.alter_column(
        "collection_items",
        "collection_id",
        existing_type=postgresql.UUID(),
        nullable=True,
    )
    # ### end Alembic commands ###
