"""Add timestamps to schools

Revision ID: 9aeaa2d68970
Revises: c4218bd700a5
Create Date: 2022-02-10 14:32:54.143062

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9aeaa2d68970"
down_revision = "c4218bd700a5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schools",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "schools",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schools", "updated_at")
    op.drop_column("schools", "created_at")
    # ### end Alembic commands ###
