"""Add subscription expiration

Revision ID: 9cfb4e3c02b2
Revises: a91a4fa643f5
Create Date: 2022-12-17 11:37:57.729637

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9cfb4e3c02b2"
down_revision = "a91a4fa643f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions", sa.Column("expiration", sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "expiration")
    # ### end Alembic commands ###
