"""Remove author from series

Revision ID: a2ae7610e3e1
Revises: 0821a5c94c12
Create Date: 2022-01-26 23:35:10.064312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ae7610e3e1'
down_revision = '0821a5c94c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_series_author_id', table_name='series')
    op.drop_constraint('fk_authors_series', 'series', type_='foreignkey')
    op.drop_column('series', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_authors_series', 'series', 'authors', ['author_id'], ['id'])
    op.create_index('ix_series_author_id', 'series', ['author_id'], unique=False)
    # ### end Alembic commands ###
