"""Create original tables

Revision ID: a65ff088f9ae
Revises: 
Create Date: 2021-12-27 10:15:54.848632

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a65ff088f9ae"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column("id", sa.String(length=3), nullable=False),
        sa.Column("phonecode", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_countries_id"), "countries", ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("countries")
    # ### end Alembic commands ###
