"""Make ReadingAbility:LabelSet M:M

Revision ID: a8d904a525af
Revises: b382aeb2f56d
Create Date: 2022-03-09 19:56:53.375726

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "a8d904a525af"
down_revision = "b382aeb2f56d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reading_abilities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_reading_abilities_key"), "reading_abilities", ["key"], unique=True
    )
    op.drop_column("labelsets", "reading_ability")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "labelsets",
        sa.Column(
            "reading_ability",
            postgresql.ENUM(
                "SPOT",
                "CAT_HAT",
                "TREEHOUSE",
                "CHARLIE_CHOCOLATE",
                "HARRY_POTTER",
                name="readingability",
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_reading_abilities_key"), table_name="reading_abilities")
    op.drop_table("reading_abilities")
    # ### end Alembic commands ###
