"""relate subscriptions to parents

Revision ID: a91a4fa643f5
Revises: 9582b1d4da88
Create Date: 2022-12-16 13:55:01.105449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a91a4fa643f5'
down_revision = '9582b1d4da88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_index('ix_subscriptions_user_id', table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_parent_id'), 'subscriptions', ['parent_id'], unique=False)
    op.drop_constraint('fk_user_stripe_subscription', 'subscriptions', type_='foreignkey')
    op.create_foreign_key('fk_parent_stripe_subscription', 'subscriptions', 'parents', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_column('subscriptions', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_parent_stripe_subscription', 'subscriptions', type_='foreignkey')
    op.create_foreign_key('fk_user_stripe_subscription', 'subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_subscriptions_parent_id'), table_name='subscriptions')
    op.create_index('ix_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    op.drop_column('subscriptions', 'parent_id')
    # ### end Alembic commands ###
