"""Add json INFO column to events

Revision ID: a9a0c79362f9
Revises: 13ca81ae5800
Create Date: 2022-03-31 10:28:58.841927

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "a9a0c79362f9"
down_revision = "13ca81ae5800"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("info", sa.JSON(), nullable=True))
    op.drop_index("ix_events_level", table_name="events")
    op.create_index(op.f("ix_events_timestamp"), "events", ["timestamp"], unique=False)
    op.create_index(op.f("ix_events_title"), "events", ["title"], unique=False)
    op.drop_constraint("fk_event_db_job", "events", type_="foreignkey")
    op.drop_column("events", "db_job_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column("db_job_id", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key("fk_event_db_job", "events", "db_jobs", ["db_job_id"], ["id"])
    op.drop_index(op.f("ix_events_title"), table_name="events")
    op.drop_index(op.f("ix_events_timestamp"), table_name="events")
    op.create_index("ix_events_level", "events", ["level"], unique=False)
    op.drop_column("events", "info")

    # ### end Alembic commands ###
