"""Add index to collectionitem isbn

Revision ID: af40ae7f818d
Revises: 4718ffb80541
Create Date: 2022-03-04 20:59:07.723662

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "af40ae7f818d"
down_revision = "4718ffb80541"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_collection_items_edition_isbn"),
        "collection_items",
        ["edition_isbn"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_collection_items_edition_isbn"), table_name="collection_items"
    )
    # ### end Alembic commands ###
