"""Update name_key computation pt.2

Revision ID: b007a39a80cf
Revises: 63b677b9d91f
Create Date: 2022-03-08 21:38:30.592489

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b007a39a80cf"
down_revision = "63b677b9d91f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "authors",
        sa.Column(
            "name_key",
            sa.String(length=400),
            sa.Computed(
                "LOWER(REGEXP_REPLACE(COALESCE(first_name, '') || last_name, '\\W|_', '', 'g'))",
            ),
            nullable=True,
        ),
    )
    op.create_index(op.f("ix_authors_name_key"), "authors", ["name_key"], unique=True)
    op.add_column(
        "illustrators",
        sa.Column(
            "name_key",
            sa.String(length=400),
            sa.Computed(
                "LOWER(REGEXP_REPLACE(COALESCE(first_name, '') || last_name, '\\W|_', '', 'g'))",
            ),
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_illustrators_name_key"), "illustrators", ["name_key"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_illustrators_name_key"), table_name="illustrators")
    op.drop_column("illustrators", "name_key")
    op.drop_index(op.f("ix_authors_name_key"), table_name="authors")
    op.drop_column("authors", "name_key")
    # ### end Alembic commands ###
