"""Complete link from LabelSet to ReadingAbility

Revision ID: b4e7bf4be9b6
Revises: a8d904a525af
Create Date: 2022-03-09 19:58:59.078750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4e7bf4be9b6'
down_revision = 'a8d904a525af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labelset_reading_ability_association',
    sa.Column('labelset_id', sa.Integer(), nullable=False),
    sa.Column('reading_ability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['labelset_id'], ['labelsets.id'], name='fk_labelset_reading_ability_association_labelset_id'),
    sa.ForeignKeyConstraint(['reading_ability_id'], ['reading_abilities.id'], name='fk_labelset_reading_ability_association_reading_ability_id'),
    sa.PrimaryKeyConstraint('labelset_id', 'reading_ability_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labelset_reading_ability_association')
    # ### end Alembic commands ###
