"""test renaming joshua

Revision ID: b5f5a596a948
Revises: 71e29ec7b49b
Create Date: 2022-12-06 15:38:27.287514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b5f5a596a948"
down_revision = "71e29ec7b49b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        'UPDATE users SET name = "Joshua LandyCool" WHERE email = "joshua@wriveted.com"'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        'UPDATE users SET name = "Joshua Landy" WHERE email = "joshua@wriveted.com"'
    )
    # ### end Alembic commands ###
