"""Add partial event indexes

Revision ID: b7bcf77d3502
Revises: 3f64a400d9fe
Create Date: 2022-06-04 21:07:32.810638

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "b7bcf77d3502"
down_revision = "3f64a400d9fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_events_school",
        "events",
        ["school_id"],
        unique=False,
        postgresql_where=sa.text("school_id IS NOT NULL"),
    )
    op.create_index(
        "ix_events_user",
        "events",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.alter_column(
        "students", "class_group_id", existing_type=postgresql.UUID(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "students", "class_group_id", existing_type=postgresql.UUID(), nullable=True
    )
    op.drop_index(
        "ix_events_user",
        table_name="events",
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_events_school",
        table_name="events",
        postgresql_where=sa.text("school_id IS NOT NULL"),
    )
    # ### end Alembic commands ###
