"""Add to schoolstate enum

Revision ID: b818487c8cc6
Revises: c3c83bc3f558
Create Date: 2022-02-08 16:49:32.135784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b818487c8cc6"
down_revision = "c3c83bc3f558"
branch_labels = None
depends_on = None


new_state = sa.Enum("PENDING", "ACTIVE", "INACTIVE", name="schoolstate")
old_state = sa.Enum("ACTIVE", "INACTIVE", name="schoolstate")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE schoolstate RENAME TO schoolstate_old")
    op.execute("CREATE TYPE schoolstate AS ENUM('PENDING', 'ACTIVE', 'INACTIVE')")
    op.alter_column(
        "schools", "state", type_=new_state, postgresql_using="state::text::schoolstate"
    )
    op.execute("DROP TYPE schoolstate_old")
    op.alter_column("schools", "official_identifier", nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "schools", "official_identifier", nullable=False, server_default="-"
    )
    op.execute("ALTER TYPE schoolstate RENAME TO schoolstate_old")
    op.execute("CREATE TYPE schoolstate AS ENUM('ACTIVE', 'INACTIVE')")
    op.alter_column(
        "schools", "state", type_=old_state, postgresql_using="state::text::schoolstate"
    )
    op.execute("DROP TYPE schoolstate_old")
    # ### end Alembic commands ###
