"""rename edition.ISBN to isbn

Revision ID: b943f85ccc3d
Revises: df0c4f0420b7
Create Date: 2022-02-22 20:09:32.771862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b943f85ccc3d'
down_revision = 'df0c4f0420b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_editions_ISBN', table_name='editions')
    op.alter_column('editions', 'ISBN', new_column_name='isbn')
    op.create_index(op.f('ix_editions_isbn'), 'editions', ['isbn'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_editions_isbn'), table_name='editions')
    op.alter_column('editions', 'isbn', new_column_name='ISBN')
    op.create_index('ix_editions_ISBN', 'editions', ['ISBN'], unique=False)
    # ### end Alembic commands ###
