"""rename edition.ISBN to isbn

Revision ID: b943f85ccc3d
Revises: df0c4f0420b7
Create Date: 2022-02-22 20:09:32.771862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b943f85ccc3d'
down_revision = 'df0c4f0420b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('editions', sa.Column('isbn', sa.String(length=200), nullable=False))
    op.drop_index('ix_editions_ISBN', table_name='editions')
    op.create_index(op.f('ix_editions_isbn'), 'editions', ['isbn'], unique=True)
    op.drop_column('editions', 'ISBN')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('editions', sa.Column('ISBN', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_editions_isbn'), table_name='editions')
    op.create_index('ix_editions_ISBN', 'editions', ['ISBN'], unique=False)
    op.drop_column('editions', 'isbn')
    # ### end Alembic commands ###
