"""Add work to most recent labelset index

Revision ID: bef0307ae2c2
Revises: 88f57e4323b4
Create Date: 2022-08-22 20:22:25.855786

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "bef0307ae2c2"
down_revision = "88f57e4323b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "index_work_labelsets",
        "labelsets",
        ["work_id", sa.text("id DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("index_work_labelsets", table_name="labelsets")
    # ### end Alembic commands ###
