"""add communications flags to supporterXreader

Revision ID: c82cfb47da40
Revises: 40c5b7fae8e1
Create Date: 2023-02-18 23:14:30.102396

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c82cfb47da40"
down_revision = "40c5b7fae8e1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "supporter_reader_association",
        sa.Column("allow_phone", sa.Boolean(), nullable=False, server_default="0"),
    )
    op.add_column(
        "supporter_reader_association",
        sa.Column("allow_email", sa.Boolean(), nullable=False, server_default="1"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("supporter_reader_association", "allow_email")
    op.drop_column("supporter_reader_association", "allow_phone")
    # ### end Alembic commands ###
