"""Adjust edition titles

Revision ID: cef2d44dd799
Revises: 956cf011085f
Create Date: 2021-12-27 11:32:12.525978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef2d44dd799'
down_revision = '956cf011085f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('editions', sa.Column('edition_title', sa.String(length=100), nullable=True))
    op.drop_column('editions', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('editions', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('editions', 'edition_title')
    # ### end Alembic commands ###
