"""Instead of is_superuser use user.type

Revision ID: d6ecaad56414
Revises: abd0a1ea9168
Create Date: 2022-02-01 21:41:35.714416

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d6ecaad56414"
down_revision = "abd0a1ea9168"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "create type enum_user_account_type as ENUM ('WRIVETED', 'LMS', 'LIBRARY', 'STUDENT', 'PUBLIC')"
    )
    op.add_column(
        "users",
        sa.Column(
            "type",
            sa.Enum(
                "WRIVETED",
                "LMS",
                "LIBRARY",
                "STUDENT",
                "PUBLIC",
                name="enum_user_account_type",
            ),
            nullable=False,
            server_default="PUBLIC",
        ),
    )
    op.create_index(op.f("ix_users_type"), "users", ["type"], unique=False)
    op.execute("commit")
    op.execute("update users set type = 'WRIVETED' where is_superuser = True")
    op.drop_column("users", "is_superuser")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_superuser", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_users_type"), table_name="users")
    op.drop_column("users", "type")
    op.execute("DROP TYPE enum_user_account_type")
    # ### end Alembic commands ###
