"""Add unique constraint on editions per school collection

Revision ID: ded4fe3ab668
Revises: 948ff66b643d
Create Date: 2022-01-16 10:48:21.822396

"""

# revision identifiers, used by Alembic.
from sqlalchemy import orm

from alembic import op
from app.models import CollectionItem

revision = "ded4fe3ab668"
down_revision = "948ff66b643d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    session.query(CollectionItem).delete()

    op.create_unique_constraint(
        "unique_editions_per_collection",
        "collection_items",
        ["school_id", "edition_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "unique_editions_per_collection", "collection_items", type_="unique"
    )
    # ### end Alembic commands ###
