"""add hydrated bool to edition

Revision ID: df0c4f0420b7
Revises: 128753c814af
Create Date: 2022-02-21 17:15:03.557484

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "df0c4f0420b7"
down_revision = "128753c814af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("editions", sa.Column("hydrated", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("editions", "hydrated")
    # ### end Alembic commands ###
