"""update labelset

Revision ID: e4529adaa763
Revises: 38ba808dac76
Create Date: 2022-03-06 23:25:46.308328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e4529adaa763'
down_revision = '38ba808dac76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    recommendstatus = sa.Enum('GOOD', 'BAD_BORING', 'BAD_REFERENCE', 'BAD_CONTROVERSIAL', 'BAD_LOW_QUALITY', name='recommendstatus')
    # This will create the enum if it's not already present which is helpful
    recommendstatus.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "labelsets",
        sa.Column(
            "recommend_status",
            recommendstatus,
            nullable=False,
            server_default="GOOD",
        ),
    )
    op.drop_column('labelsets', 'lexile')
    op.drop_column('labelsets', 'doe_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labelsets', sa.Column('doe_code', postgresql.ENUM('DOE_2G', 'DOE_2H', 'DOE_2I', 'DOE_2J', 'DOE_2K', 'DOE_2L', 'DOE_3G', 'DOE_3H', 'DOE_3I', 'DOE_3J', 'DOE_3K', 'DOE_3L', 'DOE_4G', 'DOE_4H', 'DOE_4I', 'DOE_4J', 'DOE_4K', 'DOE_4L', name='doecode'), autoincrement=False, nullable=True))
    op.add_column('labelsets', sa.Column('lexile', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.drop_column('labelsets', 'recommend_status')
    op.execute("DROP TYPE recommendstatus")
    recommendstatus = sa.Enum(name="recommendstatus")
    recommendstatus.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###