"""add product table and relationships

Revision ID: e4c494dc08fb
Revises: 91e5459d022e
Create Date: 2022-12-13 15:06:56.381097

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e4c494dc08fb"
down_revision = "91e5459d022e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("subscriptions", sa.Column("product_id", sa.String(), nullable=False))
    op.create_index(
        op.f("ix_subscriptions_product_id"),
        "subscriptions",
        ["product_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_product_stripe_subscription",
        "subscriptions",
        "products",
        ["product_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_product_stripe_subscription", "subscriptions", type_="foreignkey"
    )
    op.drop_index(op.f("ix_subscriptions_product_id"), table_name="subscriptions")
    op.drop_column("subscriptions", "product_id")
    op.drop_table("products")
    # ### end Alembic commands ###
