"""Add wriveted identifier to schools

Revision ID: e59c3ceb5830
Revises: d6ecaad56414
Create Date: 2022-02-03 15:06:19.258580

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "e59c3ceb5830"
down_revision = "d6ecaad56414"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schools",
        sa.Column(
            "wriveted_identifier",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_schools_wriveted_identifier"),
        "schools",
        ["wriveted_identifier"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_schools_wriveted_identifier"), table_name="schools")
    op.drop_column("schools", "wriveted_identifier")
    # ### end Alembic commands ###
