"""add supporter table and relationships

Revision ID: e5ac1e7a54cd
Revises: f99ef8f753ac
Create Date: 2023-02-16 17:24:24.882178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e5ac1e7a54cd"
down_revision = "f99ef8f753ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "supporters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=False),
        sa.Column("supporter_info", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"], ["users.id"], name="fk_supporter_inherits_user", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["parents.id"], name="fk_supporter_parent"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_supporters_parent_id"), "supporters", ["parent_id"], unique=False
    )
    op.create_table(
        "supporter_reader_association",
        sa.Column("supporter_id", sa.UUID(), nullable=False),
        sa.Column("reader_id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reader_id"], ["readers.id"], name="fk_supporter_reader_assoc_reader_id"
        ),
        sa.ForeignKeyConstraint(
            ["supporter_id"],
            ["supporters.id"],
            name="fk_supporter_reader_assoc_supporter_id",
        ),
        sa.PrimaryKeyConstraint("supporter_id", "reader_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("supporter_reader_association")
    op.drop_index(op.f("ix_supporters_parent_id"), table_name="supporters")
    op.drop_table("supporters")
    # ### end Alembic commands ###
