"""Add Work:BookList relationship

Revision ID: e7516505ec52
Revises: ee0d0bd84f15
Create Date: 2022-01-23 21:33:24.272621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e7516505ec52"
down_revision = "ee0d0bd84f15"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
