"""equalise first and fullnames for authors and illustrators

Revision ID: ea7b2dd2b6de
Revises: 6f2009c544e3
Create Date: 2022-02-21 12:50:29.230746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ea7b2dd2b6de"
down_revision = "6f2009c544e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "authors", sa.Column("first_name", sa.String(length=200), nullable=False)
    )
    op.create_index(
        op.f("ix_authors_first_name"), "authors", ["first_name"], unique=False
    )
    op.create_unique_constraint(None, "illustrators", ["full_name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "illustrators", type_="unique")
    op.drop_index(op.f("ix_authors_first_name"), table_name="authors")
    op.drop_column("authors", "first_name")
    # ### end Alembic commands ###
