"""Rename school:users to school:students

Revision ID: ef00fddd2595
Revises: b818487c8cc6
Create Date: 2022-02-08 20:47:45.718722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ef00fddd2595"
down_revision = "b818487c8cc6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("school_id_as_student", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        "fk_student_school", "users", "schools", ["school_id_as_student"], ["id"]
    )
    op.drop_column("users", "school_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("school_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint("fk_student_school", "users", type_="foreignkey")
    op.drop_column("users", "school_id_as_student")
    # ### end Alembic commands ###
