"""Make labelset checked notnull

Revision ID: f61643916398
Revises: 1160a11c1f73
Create Date: 2022-03-09 22:51:10.095817

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f61643916398"
down_revision = "1160a11c1f73"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("labelsets", "checked", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("labelsets", "checked", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
