"""Add optional school to subscription table

Revision ID: f791ba4a67c8
Revises: 71cb2ac1c707
Create Date: 2024-03-27 20:13:21.808888

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "f791ba4a67c8"
down_revision = "71cb2ac1c707"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "illustrators",
        "info",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "schools",
        "info",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )

    op.alter_column(
        "series",
        "info",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.add_column("subscriptions", sa.Column("school_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_subscriptions_school_id"), "subscriptions", ["school_id"], unique=False
    )
    op.create_foreign_key(
        "fk_school_stripe_subscription",
        "subscriptions",
        "schools",
        ["school_id"],
        ["wriveted_identifier"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_school_stripe_subscription", "subscriptions", type_="foreignkey"
    )
    op.drop_index(op.f("ix_subscriptions_school_id"), table_name="subscriptions")
    op.drop_column("subscriptions", "school_id")
    op.alter_column(
        "series",
        "info",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )

    op.alter_column(
        "schools",
        "info",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "illustrators",
        "info",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
