"""add supporter to user enum

Revision ID: fd903b0deff7
Revises: 4f7496e524b6
Create Date: 2023-02-18 21:36:22.634027

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "fd903b0deff7"
down_revision = "4f7496e524b6"
branch_labels = None
depends_on = None


def upgrade():
    # unfortunately the cleanest way to update enums in alembic is to use raw sql

    # temporarily switch to text as we need to update rows, but new enum values cannot be accessed in this transaction
    op.execute("ALTER TABLE users ALTER COLUMN type TYPE text USING type::text")

    # remove constraint to be able to modify
    op.execute("ALTER TABLE users ALTER COLUMN type DROP DEFAULT")

    # now update the underlying enum type, then switch the column back to enum
    op.execute("ALTER TYPE enum_user_account_type RENAME TO enum_user_account_type_old")
    op.execute(
        "CREATE TYPE enum_user_account_type AS ENUM('EDUCATOR', 'PARENT', 'PUBLIC', 'SCHOOL_ADMIN', 'STUDENT', 'SUPPORTER', 'WRIVETED')"
    )
    op.execute(
        "ALTER TABLE users ALTER COLUMN type TYPE enum_user_account_type USING type::text::enum_user_account_type"
    )
    op.execute("DROP TYPE enum_user_account_type_old")

    # return the constraint
    op.execute("ALTER TABLE users ALTER COLUMN type SET DEFAULT 'PUBLIC'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users ALTER COLUMN type TYPE text USING type::text")
    op.execute("ALTER TABLE users ALTER COLUMN type DROP DEFAULT")

    op.execute("ALTER TYPE enum_user_account_type RENAME TO enum_user_account_type_old")
    op.execute(
        "CREATE TYPE enum_user_account_type AS ENUM('EDUCATOR', 'PARENT', 'PUBLIC', 'SCHOOL_ADMIN', 'STUDENT', 'WRIVETED')"
    )
    op.execute(
        "ALTER TABLE users ALTER COLUMN type TYPE enum_user_account_type USING type::text::enum_user_account_type"
    )
    op.execute("DROP TYPE enum_user_account_type_old")

    op.execute("ALTER TABLE users ALTER COLUMN type SET DEFAULT 'PUBLIC'")
    # ### end Alembic commands ###
